### ISSUE TITLE
about the virial stress calculation in lammps

### ISSUE THREAD

**Issue by songzhigong** [CompPhysVienna/n2p2#10] opened 2019-03-03 16:46 UTC
Hi, I found there might be sometingh wrong with the lammps interface
     When I train a NNP, and test it in lammps. I found that the compute stress/atom item is invalid。
https://lammps.sandia.gov/doc/compute_stress_atom.html
     stress distribution cannot be reported normally.

Best

**Comment by singraber** [comment] 2019-03-04 07:19
Hey,

interesting.. I never used the stress/atom compute before, so there could indeed be a bug. Can you send me a minimal working example which allows me to reproduce the error?

Best,
Andi

**Comment by songzhigong** [comment] 2019-03-11 04:03
Dear Dr Andreas

     Sorry for the delay reply. lots of due came last week.  I make a test
file in the attachment. It is a unaxial tension of graphene superlattice.
The virial stress is not computed and printed correctly. However, from the
pressure (pxx, pyy), we can derive the proper stress in x or y direction.
It matches with DFT very well. So I am guessing the data flow in the source
code may need to be modified. The program can compute the atomic stress,
but is not  presented in the lammps compute item.
      I am still testing the NNP., so the attached file is not the final
version. So I do not make it public and avoid any misunderstanding.


Best
Zhigong

**Comment by singraber** [comment] 2019-03-28 08:41
Dear Zhigong,

unfortunately I did not get the attachment, can you maybe send it again directly to my university email address ( andreas dot singraber at tuwien dot ac dot at )?

Best,
Andi

**Comment by singraber** [comment] 2019-04-29 10:52
Dear Zhigong,

apologies again for the delayed reply but only recently I had some time to
investigate the problem.

As you mentioned, when one includes the `compute stress/atom` command in the
LAMMPS script the output seems to be always 0. Looking into the LAMMPS source
code (in particular `compute_stress_atom.cpp`) I found that the relevant array
which should be filled by nonzero values is called `vatom`. In the case of the
NNP pair style this array is only touched when the `ev_tally()` function (see
`pair.cpp`) is called. However, with the given arguments `vatom` is actually not
changed (e.g. the argument `fpair` must be nonzero). So, at this point I became
a little bit suspicious whether it's even possible to provide all neccessary
quantities to compute a per-atom stress...

In fact, at this point I believe that it's certainly not simple. If you have a
look at the definition of the per-atom stress tensor on the LAMMPS help page at
https://lammps.sandia.gov/doc/compute_stress_atom.html you'll notice that in the
formula there are several terms corresponding to pairwise, bond, angle, dihedral
and other types of interaction. Let's consider only the second term which treats
pairwise interactions. In the description below the formula the manual states:

> "The second term is a pairwise energy contribution where n loops over the Np
> neighbors of atom I, r1 and r2 are the positions of the 2 atoms in the pairwise
> interaction, and F1 and F2 are the forces on the 2 atoms resulting from the
> pairwise interaction."

So I assume that F1 and F2 are not the full forces on atoms 1 and 2 but rather
only the pairwise contributions. This kind of split-up into force contributions
may be simple for pairwise interactions but unfortunately the situation is more
complex if NNPs are used instead. Since NNPs are true many-body potentials there
is no easy way of splitting the interaction in pairwise (or bond or angle or
dihedral) parts. Hence, I believe that none of the terms provided in the formula
of the help page would be fitting in the case of NNPs. Instead, one would need
to follow the recipe given a little further down the help page, where it says:

> "Details of how LAMMPS computes the virial for individual atoms for either
> pairwise or many-body potentials, and including the effects of periodic boundary
> conditions is discussed in (Thompson). The basic idea for many-body potentials
> is to treat each component of the force computation between a small cluster of
> atoms in the same manner as in the formula above for bond, angle, dihedral, etc
> interactions. Namely the quantity R dot F is summed over the atoms in the
> interaction, with the R vectors unwrapped by periodic boundaries so that the
> cluster of atoms is close together. The total contribution for the cluster
> interaction is divided evenly among those atoms."

I think that in the case of NNPs the described clusters of atoms then correspond
to those involved in the calculations of the atomic energy contributions, i.e.
the neighbors of each atom within the cutoff. From my experience with
implementing the force calculation in LAMMPS I believe that there are probably
some similiarities to the force summation if one wants to implement also the
per-atom virial but I can not estimate how difficult this will be. I'm also
unsure whether there is another comparable many-body potential in LAMMPS for
which this feature is already available... that would be a good starting point.

Unfortunately, I'm afraid I don't have the time to implement this for you, but I can
certainly assist if you want to try it! The force calculation is done in the
file `InterfaceLammps.cpp` in the function `getForces()` to get you started. I
also believe it would be crucial to understand the (Thompson) reference given in the
LAMMPS manual.

The question if of course whether you really depend on this feature for your
simulations? It is one thing to be able calculate this quantity and another one
whether there is actually a meaningful interpretation. Is it clear what the
per-atom stress means in the case of many-body potentials? Do you think it is
worth the effort?

All the best,

Andi

**Comment by songzhigong** [comment] 2019-04-29 19:08
Dear Andreas

    Thanks a lot for your helpful suggestions. I will try to implement it
first.
    Actually, before I asked for your help, I had checked the code and
found it not easy. All I need to do is to code the pairwise interaction (2
body) and triplet interaction (3 body), respectively. BTW, do you suggest I
need to reshape the whole framework? If so, I may have to think it over.

Best
Zhigong

Andreas Singraber <notifications@github.com> 于2019年4月29日周一 上午6:52写道：

**Comment by singraber** [comment] 2019-04-29 22:14
Dear Zhigong,

I'm afraid there is a little misconception here..

The NNP energy can NOT be written as a simple sum of two- and three-body terms (such as e.g. a Stillinger-Weber potential), even if the radial and angular symmetry functions seem to suggest this. Instead, these atomic environment descriptors are used as an input to a neural network, which combines all descriptors in the input layer in a non-linear (!) way. Hence, the atomic energy contributions cannot be split up afterwards into pair and triplet interactions and you can not follow the formula for per-atom stress as given in the LAMMPS help page. As I mentioned above I still think there is a (complicated) way to do a per-atom stress if you follow the second LAMMPS quote. However, I think there may be a lot of code changes required and I'm not even sure if some changes must be made even in LAMMPS. I strongly suggest to reconsider your plan on how to implement this.

Best,

Andi

**Comment by songzhigong** [comment] 2019-04-29 23:47
Dear Andears

   I am grateful for your rapid reply. I will digest your algrithum first
and have a careful consideration.

best
Zhigong

Andreas Singraber <notifications@github.com> 于2019年4月29日周一 下午6:14写道：

**Comment by songzhigong** [comment] 2019-04-30 02:19
Dear Andears

    I just got an idea. Can I make a compromise by coding a post-processing
program, since I have all of the weight, symmetry function, activation
function, neural network structure, all of the atom coordinates. I can
extract lots of atomic information if I have the formula, right?

Best

Andreas Singraber <notifications@github.com> 于2019年4月29日周一 下午6:14写道：

**Comment by singraber** [comment] 2019-04-30 08:51
Dear Zhigong,

that's certainly an option... if you want to find irregularities in your configurations, e.g. atoms which are in an anomalous environment, you could analyze the symmetry functions directly along a trajectory.. maybe with an outlier detection algorithm. I would also prefer to do this in a post-processing step. Maybe one of the existing tools can simplify the process for you: `nnp-scaling` is supposed to be a tool which calculates the symmetry functions of an entire data set before training.. but in your case you could also use it to write out the symmetry function values of a trajectory instead. The tool will provide a file which contains all symmetry functions (`function.data`) and also histogram files for each symmetry function separately. Have a look at the (not yet completed) documentation: https://compphysvienna.github.io/n2p2/Tools/nnp-scaling.html

If you're ok I will close this issue.. if you have problems with your new approach, just open a new issue.

Best,

Andi

**Comment by songzhigong** [comment] 2019-04-30 14:29
Dear Andi

    Thanks a lot for your help and answers. Please close this issue.

Best

Andreas Singraber <notifications@github.com> 于2019年4月30日周二 上午4:51写道：

**Closed** 2019-04-30 17:24 UTC
